### ISSUE TITLE
It needs opportunity for cheerio configuration

### ISSUE THREAD

**Issue by mbatyumov** [Email-builder/email-builder-core#11]
I use grunt-email-builder and I have not opportunity to set xmlMode to true for cheerio options.

lib/utils.js has inline options at 59 line.

See this comment
https://github.com/Email-builder/grunt-email-builder/issues/43#issuecomment-185785923

**Comment by jeremypeter** [comment]
Should be resolved...please see https://github.com/Email-builder/grunt-email-builder/issues/43#issuecomment-185909760
