### ISSUE TITLE
Does not read entire file 

### ISSUE THREAD

**Issue by jeremypeter** [Email-builder/email-builder-core#5]
https://github.com/Email-builder/grunt-email-builder/issues/42#issuecomment-98677206

**Comment by yargalot** [comment]
So it was a buffer issue? Random.

**Comment by jeremypeter** [comment]
It was a streaming issue. I'm using [streams](https://github.com/Email-builder/email-builder-core/blob/master/lib/emailBuilder.js#L64) to read the file which reads the file in chunks of data at a time. If the file was large, it was only returning the first chunk of data and not the rest. So I add the [es.wait](https://github.com/Email-builder/email-builder-core/blob/master/lib/emailBuilder.js#L67) method to tell the stream to wait for all the data to come through before exiting.
